version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build with Tests
          #command: mvn clean package
          command: echo "Building"
  
  deploy-dev:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: 
          command: echo "Deploying in DEV"
      #- run:
      #    command: mvn -DskipTests deploy -DmuleDeploy -Dmule.version=4.4.0 -Danypoint.username="$ANYPOINT_USER" -Danypoint.password="$ANYPOINT_PASSWORD" -Dcloudhub.app="hello-world-dev" -Dcloudhub.environment="DEV" -Dcloudhub.bg="Mulesoft" -Dcloudhub.worker="1" -Dcloudhub.workerType="MICRO" -Dmule.env="dev" -Denc.key="$ENC_KEY" -Dcloudhub.region="ap-southeast-2" -Danypoint.platform.client_id="$PLATFORM_CLIENTID" -Danypoint.platform.client_secret="$PLATFORM_CLIENTSECRET"

  hold-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          command: echo "Approve Deployment in Test"
  
  deploy-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: 
          command: echo "Deploying in TEST"
      #- run:
      #    command: mvn -DskipTests deploy -DmuleDeploy -Dmule.version=4.4.0 -Danypoint.username="$ANYPOINT_USER" -Danypoint.password="$ANYPOINT_PASSWORD" -Dcloudhub.app="hello-world-test" -Dcloudhub.environment="TEST" -Dcloudhub.bg="Mulesoft" -Dcloudhub.worker="1" -Dcloudhub.workerType="MICRO" -Dmule.env="test" -Denc.key="$ENC_KEY" -Dcloudhub.region="ap-southeast-2" -Danypoint.platform.client_id="$PLATFORM_CLIENTID" -Danypoint.platform.client_secret="$PLATFORM_CLIENTSECRET"

  hold-uat:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          command: echo "Approve Deployment in UAT"
  
  deploy-uat:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: 
          command: echo "Deploying in UAT"
      #- run:
      #    command: mvn -DskipTests deploy -DmuleDeploy -Dmule.version=4.4.0 -Danypoint.username="$ANYPOINT_USER" -Danypoint.password="$ANYPOINT_PASSWORD" -Dcloudhub.app="hello-world-uat" -Dcloudhub.environment="UAT" -Dcloudhub.bg="Mulesoft" -Dcloudhub.worker="1" -Dcloudhub.workerType="MICRO" -Dmule.env="uat" -Denc.key="$ENC_KEY" -Dcloudhub.region="ap-southeast-2" -Danypoint.platform.client_id="$PLATFORM_CLIENTID" -Danypoint.platform.client_secret="$PLATFORM_CLIENTSECRET"
  
  hold-prod:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          command: echo "Approve Deployment in Prod"          
  
  deploy-prod:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: 
          command: echo "Deploying in Prod"
      #- run:
      #    command: mvn -DskipTests deploy -DmuleDeploy -Dmule.version=4.4.0 -Danypoint.username="$ANYPOINT_USER" -Danypoint.password="$ANYPOINT_PASSWORD" -Dcloudhub.app="hello-world" -Dcloudhub.environment="PROD" -Dcloudhub.bg="Mulesoft" -Dcloudhub.worker="1" -Dcloudhub.workerType="MICRO" -Dmule.env="prod" -Denc.key="$ENC_KEY" -Dcloudhub.region="ap-southeast-2" -Danypoint.platform.client_id="$PLATFORM_CLIENTID" -Danypoint.platform.client_secret="$PLATFORM_CLIENTSECRET"
      
      
      
workflows:
  dev-workflow: 
    when: 
      equal: [ develop, << pipeline.git.branch >> ]
    jobs:
      - build-and-test
      - deploy-dev:
          requires:
              - build-and-test
          context: Anypoint
      - hold-test:
          type: approval
          requires:
              - build-and-test
              - deploy-dev
      - deploy-test:
          requires:
              - hold-test
          context: Anypoint
      - hold-uat:
          type: approval
          requires:
              - deploy-test
      - deploy-uat:
          requires:
              - hold-uat
          context: Anypoint
      - hold-prod:
          type: approval
          requires:
              - deploy-uat
      - deploy-prod:
          requires:
              - hold-prod
          context: Anypoint
  
  bugfix-workflow:
    when: 
      matches:
        pattern: "hotfix\\S+" 
        value: << pipeline.git.branch >> 
    jobs:    
      - build-and-test
      - hold-uat:
          type: approval
          requires:
              - build-and-test
      - deploy-uat:
          requires:
              - hold-uat
          context: Anypoint
      - hold-prod:
          type: approval
          requires:
              - deploy-uat
      - deploy-prod:
          requires:
              - hold-prod
          context: Anypoint

  