version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build with Tests
          #command: mvn clean package
          command: echo "Building"
  
  deploy-dev:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: echo "Deploying to Dev"

  hold-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          command: echo "Approve Deployment in Test"
  
  deploy-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: echo "Deploying to Test"

  hold-uat:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          command: echo "Approve Deployment in UAT"
  
  deploy-uat:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: echo "Deploying to UAT"
            
  deploy-prod:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: echo "Deploying to Prod"
      
      
      
workflows:
  dev-workflow: 
    when: 
      equal: [ develop, << pipeline.git.branch >> ]
    jobs:
      - build-and-test
      - deploy-dev:
          requires:
              - build-and-test
          context: anypoint
      - hold-test:
          type: approval
          requires:
              - build-and-test
              - deploy-dev
      - deploy-test:
          requires:
              - hold-test
          context: anypoint
      - hold-uat:
          type: approval
          requires:
              - deploy-test
      - deploy-uat:
          requires:
              - hold-uat
          context: anypoint
  
  bugfix-workflow:
    when: 
      matches:
        pattern: "hotfix\\S+" 
        value: << pipeline.git.branch >> 
    jobs:    
      - build-and-test
      - hold-uat:
          type: approval
          requires:
              - build-and-test
      - deploy-uat:
          requires:
              - hold-uat
          context: anypoint

  release-workflow:
    when: 
      or:
        - matches:
            pattern: "release\\d{1,}/gm" 
            value: << pipeline.git.branch >> 
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:    
      - build-and-test
      - deploy-prod:
          requires:
              - build-and-test
          context: anypoint
